name: build

on:
  pull_request:
    branches: [master]
    types: [closed]
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.event.pull_request.merged == true && ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/' }}
    runs-on: macos-latest
    steps:
      - name: Generate1
        run: echo "111" > 111.txt
      - name: Generate2
        run: echo "222" > 222.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            111.txt
            222.txt
