name: build

on:
  push:
    branches:
      - master

jobs:
  build:
#    if: github.event.pull_request.merged == true && ${{ github.ref == 'refs/heads/master' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          # import keystore from secrets
          ls -all
          echo $KEYSTORE_BASE64 | base64 -d -o android/app/key.jks
          echo $KEY_PROPERTIES | base64 -d -o android/key.properties
      - run: flutter pub get
      - run: flutter build apk
#      - run: flutter build ios --release --no-codesign
      - name: Run script file
        run: |
         chmod +x .github/scripts/pgyer_upload.sh
         .github/scripts/pgyer_upload.sh -k ${{ secrets.PGYER_APIKEY }} build/app/outputs/flutter-apk/app-release.apk
        shell: bash
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@1.0.8
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHATWORK_WEBHOOK}}
        with:
          msgtype: text
          content: "updated"

